# Generated by Django 6.0.4 on 2026-05-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('severidad', models.IntegerField(blank=True, null=True)),
                ('riesgo_ia', models.CharField(blank=True, max_length=100, null=True)),
                ('explicacion_ia', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(default='Pendiente', max_length=50)),
                ('fuente', models.CharField(default='Wazuh', max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
