# Generated by Django 6.0.4 on 2026-07-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='opensearch_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
