# Generated by Django 6.0.4 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alert_opensearch_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='veredicto_ia_correcto',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
