# Generated by Django 6.0.4 on 2026-09-08 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alert_veredicto_ia_correcto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='analizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='correccion_autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcciones_alertas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='correccion_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='correccion_motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='correccion_veredicto',
            field=models.CharField(blank=True, choices=[('FALSO_POSITIVO', 'Falso positivo'), ('REQUIERE_ATENCION', 'Requiere atención')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='estado_analisis',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente de análisis'), ('COMPLETED', 'Análisis completado'), ('ANALISIS_FALLIDO', 'Fallo de análisis')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='evidencia_faltante',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='factores_cvss',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='justificacion_cvss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='modelo_ia',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='proveedor_ia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='recomendacion_ia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='respuesta_ia_original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='veredicto_ia',
            field=models.CharField(blank=True, choices=[('FALSO_POSITIVO', 'Falso positivo'), ('REQUIERE_ATENCION', 'Requiere atención')], max_length=20, null=True),
        ),
    ]
