# Generated by Django 6.0.4 on 2026-09-08 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alert_contrato_ia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoLogico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20, unique=True)),
                ('nombre_visible', models.CharField(max_length=120)),
                ('tipo_activo', models.CharField(choices=[('estacion_publica', 'Estación pública'), ('equipo_administracion', 'Equipo de administración'), ('servidor_interno', 'Servidor interno')], max_length=30)),
                ('criticidad', models.CharField(choices=[('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('os_family', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('otro', 'Otro'), ('no_determinado', 'No determinado')], default='no_determinado', max_length=20)),
                ('os_role', models.CharField(choices=[('estacion_cliente', 'Estación cliente'), ('administracion', 'Administración'), ('servidor', 'Servidor')], max_length=20)),
                ('hora_inicio_operacion', models.TimeField()),
                ('hora_fin_operacion', models.TimeField()),
                ('zona_horaria', models.CharField(default='America/Bogota', max_length=64)),
                ('contexto_autorizado_es', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'activo lógico',
                'verbose_name_plural': 'activos lógicos',
                'ordering': ['identificador'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='contexto_ia_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='motivo_omision',
            field=models.CharField(blank=True, choices=[('SIN_CONTEXTO_ACTIVO', 'Sin contexto de activo'), ('NIVEL_NO_ELEGIBLE', 'Nivel Wazuh no elegible'), ('RUIDO_OPERATIVO', 'Ruido operativo confirmado'), ('REGLA_EXCLUIDA', 'Regla o grupo excluido')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='wazuh_rule_groups',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='wazuh_rule_id',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='estado_analisis',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pendiente de análisis'), ('COMPLETED', 'Análisis completado'), ('ANALISIS_FALLIDO', 'Fallo de análisis'), ('OMITIDO_POLITICA', 'Omitido por política')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='activo_logico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='dashboard.activologico'),
        ),
    ]
