# Generated by Django 6.0.4 on 2026-09-08 (Sprint 2C, corregida pre-MySQL).
#
# ADITIVA y portable (MySQL 5.7+/8.x, MariaDB 10.x, SQLite):
#   - alert.wazuh_agent_id: columna NULLABLE nueva (capa privada P).
#   - AsignacionAgenteActivo: asignación ACTUAL, con `agent_id` UNIQUE normal.
#         MySQL/MariaDB : UNIQUE KEY sobre (`agent_id`)   -- índice único simple
#         SQLite        : "agent_id" varchar(32) NOT NULL UNIQUE
#     NO se usa UniqueConstraint(condition=...) (índice parcial), que
#     MySQL/MariaDB no garantizan. La unicidad "una asignación por agente" la
#     impone la BASE DE DATOS, no sólo Python.
#   - HistorialAsignacionAgente: bitácora append-only, sin unicidad (crece sin
#     límite).
# No contiene datos: ninguna asignación se crea por migración.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_activos_ingesta_colas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='wazuh_agent_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='AsignacionAgenteActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=32, unique=True)),
                ('etiqueta_privada', models.CharField(blank=True, default='', max_length=64)),
                ('nota', models.TextField(blank=True, default='')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('activo_logico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignacion_agente', to='dashboard.activologico')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación agente→activo (actual, privada)',
                'verbose_name_plural': 'asignaciones agente→activo (actuales, privadas)',
                'ordering': ['agent_id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAsignacionAgente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(max_length=32)),
                ('activo_identificador', models.CharField(max_length=20)),
                ('accion', models.CharField(choices=[('asignada', 'Asignada por primera vez'), ('reemplazada', 'Reemplazada por otra asignación'), ('desactivada', 'Desactivada (agente sin activo)')], max_length=12)),
                ('etiqueta_privada', models.CharField(blank=True, default='', max_length=64)),
                ('nota', models.TextField(blank=True, default='')),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('activo_logico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dashboard.activologico')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cambio de asignación agente→activo (histórico)',
                'verbose_name_plural': 'cambios de asignación agente→activo (histórico)',
                'ordering': ['-registrado_en', '-id'],
            },
        ),
    ]
