# Generated by Django 6.0.4 (Sprint 2G).
#
# ADITIVA: sólo CreateModel VentanaMantenimiento + un CHECK (fin > inicio).
# Portable: MySQL 8.x/MariaDB 10.x aplican el CHECK; SQLite también. No toca
# ninguna tabla existente ni ninguna fila. Sin RunPython, sin datos.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_resolver_agente_activo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VentanaMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('categoria', models.CharField(choices=[('actualizacion_software', 'Actualización de software / parches'), ('cambio_configuracion', 'Cambio de configuración'), ('mantenimiento_hardware', 'Mantenimiento de hardware'), ('respaldo_restauracion', 'Respaldo / restauración'), ('reinicio_servicios', 'Reinicio de servicios'), ('limpieza_housekeeping', 'Limpieza / housekeeping'), ('otro', 'Otro (ver descripción)')], max_length=30)),
                ('descripcion', models.CharField(blank=True, default='', max_length=280)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=10)),
                ('cancelada_en', models.DateTimeField(blank=True, null=True)),
                ('activo_logico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventanas_mantenimiento', to='dashboard.activologico')),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventanas_mantenimiento_canceladas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventanas_mantenimiento_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ventana de mantenimiento',
                'verbose_name_plural': 'ventanas de mantenimiento',
                'ordering': ['-inicio', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fin__gt', models.F('inicio'))), name='vm_fin_posterior_a_inicio')],
            },
        ),
    ]
