# Generated by Django 6.0.4 on 2026-10-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_legado_snapshot_y_origen_revision'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanamantenimiento',
            name='alcance_operacion',
            field=models.CharField(choices=[('gestion_cuentas_locales', 'Gestión de cuentas y grupos locales'), ('gestion_privilegios', 'Cambios de privilegios (grupos privilegiados)'), ('instalacion_actualizacion_software', 'Instalación o actualización de software'), ('configuracion_servicios', 'Configuración de servicios'), ('politica_auditoria_seguridad', 'Política de auditoría de seguridad'), ('archivos_laboratorio', 'Archivos del directorio aislado de laboratorio'), ('conexion_dispositivos', 'Conexión de dispositivos externos'), ('otro_no_tipificado', 'Otro (no tipificado)'), ('no_declarado', 'No declarado (ventana anterior al alcance)')], default='no_declarado', max_length=40),
        ),
    ]
