# Generated by Django 6.0.4 on 2026-10-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_ventana_alcance_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisioncandidato',
            name='entrada_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='revisioncandidato',
            name='salida_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='revisioncandidato',
            name='serializacion_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='EntradaRevisada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('ENTRADA_REVISADA', 'Entrada revisada: congelada al guardar el borrador'), ('SNAPSHOT_CONSERVADO', 'Histórico: snapshot conservado; solo coincide la huella semántica'), ('HUELLA_LEGADO_VERIFICADA', 'Histórico: coincide una huella completa de un algoritmo anterior'), ('DERIVADA', 'Derivada por una transformación explícita (no es la original)'), ('NO_VERIFICABLE', 'No verificable')], max_length=32)),
                ('entrada', models.JSONField()),
                ('entrada_sha256', models.CharField(max_length=64)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('serializacion_version', models.CharField(max_length=32)),
                ('seleccion_version', models.CharField(max_length=32)),
                ('algoritmo_verificacion', models.CharField(blank=True, default='', max_length=40)),
                ('transformacion_id', models.CharField(blank=True, default='', max_length=60)),
                ('motivo', models.TextField(blank=True, default='')),
                ('limitaciones', models.TextField(blank=True, default='')),
                ('creada_por', models.CharField(blank=True, default='', max_length=150)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siguiente', to='dashboard.entradarevisada')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entradas_revisadas', to='dashboard.candidatodataset')),
            ],
            options={
                'ordering': ['candidato_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmacionBorrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salida', models.JSONField()),
                ('salida_sha256', models.CharField(max_length=64)),
                ('serializacion_version', models.CharField(max_length=32)),
                ('confirmada_por', models.CharField(blank=True, default='', max_length=150)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmaciones', to='dashboard.candidatodataset')),
                ('entrada_revisada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmaciones', to='dashboard.entradarevisada')),
            ],
            options={
                'ordering': ['candidato_id', 'creada_en', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='entradarevisada',
            constraint=models.UniqueConstraint(fields=('candidato', 'version'), name='entrada_revisada_version_unica'),
        ),
    ]
