# Generated by Django 6.0.4 on 2026-10-07 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_sellos_entrada_salida'),
    ]

    operations = [
        migrations.CreateModel(
            name='AceptacionLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(max_length=24)),
                ('responsable', models.CharField(max_length=150)),
                ('responsable_id', models.PositiveIntegerField()),
                ('declaracion', models.TextField()),
                ('lista_comprobacion', models.JSONField()),
                ('lista_sha256', models.CharField(max_length=64)),
                ('referencia_revision', models.TextField()),
                ('manifiesto_sha256', models.CharField(max_length=64, unique=True)),
                ('n_casos', models.PositiveIntegerField()),
                ('serializacion_version', models.CharField(max_length=32)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['creada_en', 'id'],
            },
        ),
        migrations.AddField(
            model_name='revisioncandidato',
            name='modo_revision',
            field=models.CharField(choices=[('DOBLE', 'Doble revisión'), ('REVISOR_UNICO_LOTE', 'Revisión consolidada por lote')], default='DOBLE', max_length=24),
        ),
        migrations.AddField(
            model_name='revisioncandidato',
            name='aceptacion_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisiones', to='dashboard.aceptacionlote'),
        ),
        migrations.CreateModel(
            name='AceptacionLoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_sha256', models.CharField(max_length=64)),
                ('salida_sha256', models.CharField(max_length=64)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_lote', to='dashboard.candidatodataset')),
                ('confirmacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_lote', to='dashboard.confirmacionborrador')),
                ('entrada_revisada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_lote', to='dashboard.entradarevisada')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='dashboard.aceptacionlote')),
            ],
            options={
                'ordering': ['lote_id', 'id'],
                'constraints': [models.UniqueConstraint(fields=('candidato',), name='lote_item_candidato_unico')],
            },
        ),
    ]
