# Generated by Django 6.0.4 on 2026-10-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_aceptacion_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='activologico',
            name='horario_sin_restriccion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activologico',
            name='tipo_activo',
            field=models.CharField(choices=[('estacion_publica', 'Estación pública'), ('equipo_administracion', 'Equipo de administración'), ('servidor_interno', 'Servidor interno'), ('equipo_personal', 'Equipo personal')], max_length=30),
        ),
    ]
