"""
Django settings for sentria_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from sentria_project.env_utils import EnvFileError, localizar_env_file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carga del .env: $SENTRIA_ENV_FILE si está definido (obligatorio que exista y
# tenga permisos <=600), si no el .env local del proyecto. Ver env_utils.py.
try:
    _ENV_FILE = localizar_env_file(BASE_DIR)
except EnvFileError as _e:
    raise ImproperlyConfigured(str(_e))
if _ENV_FILE is not None:
    load_dotenv(_ENV_FILE)


def _variable_requerida(nombre):
    """
    Lee una variable de entorno obligatoria y falla de forma clara si falta.

    Nunca debe sustituirse por un valor literal de respaldo: este archivo es
    público (se versiona en el repositorio) y no puede contener secretos.
    Ver .env.example para la lista completa de variables esperadas.
    """
    valor = os.environ.get(nombre)
    if not valor:
        raise ImproperlyConfigured(
            f"Falta la variable de entorno obligatoria '{nombre}'. "
            "Copia .env.example a .env y complétala con un valor real antes "
            "de iniciar la aplicación."
        )
    return valor


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Sin valor de respaldo: una clave de Django comprometida invalida la
# protección de sesiones, mensajes firmados y tokens CSRF de todo el sitio.
SECRET_KEY = _variable_requerida('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'dashboard',
    'usuarios',
    'rest_framework',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sentria_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sentria_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# El túnel ngrok es efímero: host y puerto cambian al reiniciarse. Por eso
# DB_HOST/DB_PORT no tienen un valor de respaldo utilizable: deben venir
# siempre de .env con los datos vigentes del túnel.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'bdsentria'),
        'USER': _variable_requerida('DB_USER'),
        'PASSWORD': _variable_requerida('DB_PASSWORD'),
        'HOST': _variable_requerida('DB_HOST'),
        'PORT': _variable_requerida('DB_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/accounts/login/"
LOGIN_URL = "/accounts/login/"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# --- Módulo IA (Sprint 2C) ---------------------------------------------------
# agent.id de Wazuh que NO se asignan ni se resuelven a un ActivoLogico. Para
# habilitar uno hay que retirarlo de esta lista de forma deliberada y auditada.
# "AGENT-02" es sólo una ETIQUETA DOCUMENTAL: su agent.id real todavía no se
# conoce en este entorno, así que hoy su protección efectiva es que no existe
# ninguna asignación para él. Cuando 1C.1/1D confirme su agent.id, añadirlo aquí
# ANTES de cualquier uso. Formato en .env: IA_AGENTES_BLOQUEADOS=002,003
IA_AGENTES_BLOQUEADOS = [
    a.strip() for a in os.environ.get('IA_AGENTES_BLOQUEADOS', '').split(',') if a.strip()
]

# Overrides opcionales de la política de elegibilidad (dashboard/ia/politica.py).
# IA_POLITICA = {"nivel_minimo": 7, "grupos_excluidos": [...], ...}
